# Generated by Django 6.0.6 on 2026-06-20 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsGroup', models.BooleanField(default=False)),
                ('Name', models.CharField(blank=True, max_length=120, null=True)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CreatedChats', to=settings.AUTH_USER_MODEL)),
                ('Participants', models.ManyToManyField(related_name='Chats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.TextField()),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Messages', to='chat.chat')),
                ('Sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SentMessages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['CreatedAt'],
            },
        ),
    ]
